# Generated by Django 5.2.15 on 2026-07-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('customer_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('average_customer_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('usual_location', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('ATM', 'ATM'), ('ONLINE', 'Online'), ('MOBILE', 'Mobile'), ('BRANCH', 'Branch')], max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('is_new_device', models.BooleanField(default=False)),
                ('beneficiary_type', models.CharField(max_length=50)),
                ('is_new_beneficiary', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('previous_fraud_flag', models.BooleanField(default=False)),
                ('initial_risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('risk_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('AI_ANALYZED', 'AI Analyzed'), ('MARKED_SAFE', 'Marked Safe'), ('ESCALATED', 'Escalated to Investigation'), ('CUSTOMER_VERIFICATION_SENT', 'Customer Verification Sent')], default='PENDING_REVIEW', max_length=50)),
                ('assigned_to', models.CharField(max_length=100)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('customer_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fraud Case',
                'verbose_name_plural': 'Fraud Cases',
                'ordering': ['-transaction_time'],
            },
        ),
    ]
