# Generated by Django 5.2.16 on 2026-07-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudcase',
            name='verification_transcript',
            field=models.TextField(blank=True),
        ),
    ]
