# Generated by Django 5.2.16 on 2026-07-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_fraudcase_verification_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudcase',
            name='elevenlabs_conversation_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
